--Carga de datos
INSERT INTO sucursal (nombre, horarioApertura, horarioCierre, operativa) VALUES ('Puerto', 8, 13, 'OPERATIVA');
INSERT INTO sucursal (nombre, horarioApertura, horarioCierre, operativa) VALUES ('B', 8, 13, 'OPERATIVA');
INSERT INTO sucursal (nombre, horarioApertura, horarioCierre, operativa) VALUES ('C', 8, 13, 'OPERATIVA');
INSERT INTO sucursal (nombre, horarioApertura, horarioCierre, operativa) VALUES ('X', 8, 13, 'OPERATIVA');
INSERT INTO sucursal (nombre, horarioApertura, horarioCierre, operativa) VALUES ('D', 8, 13, 'OPERATIVA');
INSERT INTO sucursal (nombre, horarioApertura, horarioCierre, operativa) VALUES ('F', 8, 13, 'OPERATIVA');
INSERT INTO sucursal (nombre, horarioApertura, horarioCierre, operativa) VALUES ('Y', 8, 13, 'OPERATIVA');
INSERT INTO sucursal (nombre, horarioApertura, horarioCierre, operativa) VALUES ('E', 8, 13, 'OPERATIVA');
INSERT INTO sucursal (nombre, horarioApertura, horarioCierre, operativa) VALUES ('G', 8, 13, 'OPERATIVA');
INSERT INTO sucursal (nombre, horarioApertura, horarioCierre, operativa) VALUES ( 'Z', 8, 13, 'OPERATIVA');
INSERT INTO sucursal (nombre, horarioApertura, horarioCierre, operativa) VALUES ( 'Centro', 8, 13, 'OPERATIVA');

INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES (1, 2, 1, 4, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES (1, 3, 3, 6, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES (1, 4, 2, 2, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES (2, 3, 1, 5, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES (4, 3, 6, 1, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES (2, 5, 1, 8, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES (3, 5, 3, 4, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES (3, 6, 7, 10, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES (5, 6, 1, 7, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES ( 6, 7, 2, 13, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES ( 4, 7, 4, 2, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES ( 7, 10, 5, 11, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES ( 6, 9, 3, 2, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES ( 4, 9, 9, 5, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES ( 5, 8, 6, 14, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES ( 9, 8, 1, 6, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES ( 8, 11, 2, 7, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES ( 9, 11, 6, 12, 'OPERATIVA');
INSERT INTO camino (sucursalOrigen, sucursalDestino, tiempoTransito, capacidadMaxima, operativa) VALUES ( 10, 11, 9, 8, 'OPERATIVA');

INSERT INTO producto (nombre, descripcion, precioUnitario, peso) VALUES ('Camiseta de algodón', 'Camiseta de manga corta para hombres', 20, 200);
INSERT INTO producto (nombre, descripcion, precioUnitario, peso) VALUES ('Zapatos deportivos', 'Zapatos deportivos para correr', 75, 800);
INSERT INTO producto (nombre, descripcion, precioUnitario, peso) VALUES ('Laptop ASUS', 'Laptop con pantalla de 15 pulgadas', 1200, 2000);
INSERT INTO producto (nombre, descripcion, precioUnitario, peso) VALUES ('Teléfono inteligente', 'Teléfono móvil con cámara de alta resolución', 600, 150);
INSERT INTO producto (nombre, descripcion, precioUnitario, peso) VALUES ('Mesa de comedor', 'Mesa de madera para comedor con 6 sillas', 400, 3500);
INSERT INTO producto (nombre, descripcion, precioUnitario, peso) VALUES ('Cafetera', 'Máquina de café de goteo programable', 45, 1000);
INSERT INTO producto (nombre, descripcion, precioUnitario, peso) VALUES ('Juego de sartenes', 'Set de 3 sartenes antiadherentes', 30, 2500);
INSERT INTO producto (nombre, descripcion, precioUnitario, peso) VALUES ('Libro de ciencia ficción', 'Novela de ciencia ficción best-seller', 15, 500);
INSERT INTO producto (nombre, descripcion, precioUnitario, peso) VALUES ('Bicicleta de montaña', 'Bicicleta todoterreno con suspensión', 350, 12000);
INSERT INTO producto (nombre, descripcion, precioUnitario, peso) VALUES ( 'Reproductor de música', 'Reproductor MP3 con capacidad de 16GB', 30, 50);

INSERT INTO stock (stock, id_sucursal, id_producto) VALUES (23, 1, 1);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES (10, 1, 2);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES (34, 1, 3);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES (120, 1, 4);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES (63, 1, 5);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES (89, 1, 6);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES (40, 1, 7);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES (53, 1, 8);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES (276, 1, 9);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 197, 1, 10);

INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 11, 2, 1);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 28, 2, 2);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 30, 2, 3);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 160, 2, 4);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 8, 2, 5);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 25, 2, 6);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 147, 2, 7);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 50, 2, 8);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 2, 9);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 35, 2, 10);

INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 29, 3, 1);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 70, 3, 2);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 146, 3, 3);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 3, 4);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 82, 3, 5);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 94, 3, 6);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 3, 3, 7);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 20, 3, 8);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 18, 3, 9);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 39, 3, 10);

INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 4, 1);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 66, 4, 2);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 4, 3);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 40, 4, 4);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 2, 4, 5);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 19, 4, 6);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 36, 4, 7);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 13, 4, 8);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 140, 4, 9);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 14, 4, 10);

INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 73, 5, 1);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 45, 5, 2);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 88, 5, 3);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 12, 5, 4);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 60, 5, 5);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 27, 5, 6);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 93, 5, 7);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 5, 5, 8);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 36, 5, 9);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 5, 10);

INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 6, 1);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 17, 6, 2);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 6, 3);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 41, 6, 4);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 78, 6, 5);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 33, 6, 6);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 6, 7);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 70, 6, 8);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 28, 6, 9);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 87, 6, 10);

INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 54, 7, 1);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 7, 2);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 78, 7, 3);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 12, 7, 4);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 66, 7, 5);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 7, 6);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 95, 7, 7);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 33, 7, 8);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 7, 9);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 20, 7, 10);

INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 8, 1);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 68, 8, 2);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 10, 8, 3);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 88, 8, 4);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 47, 8, 5);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 72, 8, 6);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 8, 7);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 29, 8, 8);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 94, 8, 9);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 8, 10);

INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 52, 9, 1);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 36, 9, 2);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 77, 9, 3);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 14, 9, 4);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 9, 5);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 9, 6);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 81, 9, 7);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 28, 9, 8);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 94, 9, 9);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 9, 10);

INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 72, 10, 1);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 10, 2);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 88, 10, 3);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 19, 10, 4);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 56, 10, 5);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 33, 10, 6);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 61, 10, 7);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 10, 8);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 10, 9);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 10, 10);

INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 11, 1);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 11, 2);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 90, 11, 3);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 13, 11, 4);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 71, 11, 5);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 44, 11, 6);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 82, 11, 7);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 11, 8);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 97, 11, 9);
INSERT INTO stock (stock, id_sucursal, id_producto) VALUES ( 0, 11, 10);